### ISSUE TITLE
add possibility to view current limit

### ISSUE THREAD

**Issue by vincent-fuchs** [ddd-by-examples/all-things-cqrs#3]
Hi,

Viewing the list of withdrawals is good, but one interesting thing would be to also show how to sync and retrieve the credit card limit. 

For instance, I feel it's not very clear why we do this : https://github.com/ddd-by-examples/all-things-cqrs/blob/0f6bf44bd6739fc864604cdadd7c19edc602b993/with-application-events/src/main/java/io/dddbyexamples/cqrs/model/CreditCard.java#L26 

we modify the limit but it doesn't have any impact, does it ? when I comment the line, the test is still passing.

If we were to provide a GET endpoint to view the card limit, it would show how to read all withdraw events from the store to build an up to date view of the credit card.

**Comment by pilloPl** [comment]
Hi!

The code you pasted is for keeping the invariants of the aggregate in place. It validates if the command should be accepted or denied. 

That is why test for synchronizing command and queries is still passing when you comment this line. But this test does not pass:

```
 @Test
    public void shouldBeAbleToWithdrawMoney() {
        //given
        CreditCard creditCard = new CreditCard(TEN);

        //when
        creditCard.withdraw(ONE);

        //expect
        assertThat(creditCard.availableBalance()).isEqualByComparingTo(new BigDecimal(9));
        assertThat(creditCard.getWithdrawals()).hasSize(1);
        assertThat(creditCard.getWithdrawals().get(0).getAmount()).isEqualByComparingTo(ONE);
    }
```

Although it would be interesting to see rebuilidng the state from commands - this is not primary goal of this project. In Event Sourcing we build internal projection for validating commands. In our CQRS project we build projection for commands (by keeping state) and projection for reads (by keeping state).

Plus there is one module coming soon that uses event sourcing :) so your issue might get addressed

Thanks and keep posting!
